Repository AY1920S1-CS2113T-F14-4/main, pull requests merged in 2019-10, with the labels that each got.

#62 File Tracking Feature
  src/main/java/duke/Duke.java
  src/main/java/duke/Parser.java
  src/main/java/duke/Storage.java
  src/main/java/duke/commands/Command.java
  src/main/java/duke/commands/FileCommand.java
  src/main/java/duke/tasks/FileTask.java
  src/test/java/DukeTest.java
  src/test/java/FileTest.java
Labels: type.Task

#63 Refactor tasks
  src/main/java/duke/commands/SnoozeCommand.java
  src/main/java/duke/tasks/After.java
  src/main/java/duke/tasks/Deadline.java
  src/main/java/duke/tasks/Event.java
  src/main/java/duke/tasks/FileTask.java
  src/main/java/duke/tasks/Fixed.java
  src/main/java/duke/tasks/Recurring.java
  src/main/java/duke/tasks/Task.java
  src/main/java/duke/tasks/Tentative.java
  src/main/java/duke/tasks/Todo.java
  src/main/java/duke/tasks/Within.java
Labels: type.Refactor, type.Task

#64 Implement delete multiple tasks feature
  src/main/java/duke/Parser.java
  src/main/java/duke/commands/DeleteMultipleCommand.java
  src/main/java/duke/commands/DoneCommand.java
  src/test/java/DukeTest.java
Labels: type.Enhancement

#65 Include Ui mock-up and resize individual images
  README.adoc
  README.md
  docs/images/Ui.png
  docs/images/lackmoo.png
  docs/images/rssujay.png
  docs/images/tck1997.png
  docs/images/ttippinyu.png
Labels: type.Documentation

#66 Added JUnit tests for DateTime and Storage
  src/main/java/duke/DateTime.java
  src/test/java/DateTimeTest.java
  src/test/java/StorageTest.java
Labels: type.Task, v1.1

#68 Implement Item & GradedComponent classes
  src/main/java/duke/Storage.java
  src/main/java/duke/TaskList.java
  src/main/java/duke/commands/AddCommand.java
  src/main/java/duke/commands/DeleteCommand.java
  src/main/java/duke/commands/DeleteMultipleCommand.java
  src/main/java/duke/commands/DoneCommand.java
  src/main/java/duke/commands/FileCommand.java
  src/main/java/duke/commands/FindCommand.java
  src/main/java/duke/commands/FindFreeCommand.java
  src/main/java/duke/commands/ListCommand.java
  src/main/java/duke/commands/ReminderCommand.java
  src/main/java/duke/commands/SetCommand.java
  src/main/java/duke/commands/SnoozeCommand.java
  src/main/java/duke/commands/ViewScheduleCommand.java
  src/main/java/duke/items/GradedComponent.java
  src/main/java/duke/items/Item.java
  src/main/java/duke/items/tasks/After.java
  src/main/java/duke/items/tasks/Deadline.java
  src/main/java/duke/items/tasks/Event.java
  src/main/java/duke/items/tasks/FileTask.java
  src/main/java/duke/items/tasks/Fixed.java
  src/main/java/duke/items/tasks/Recurring.java
  src/main/java/duke/items/tasks/Task.java
  src/main/java/duke/items/tasks/Tentative.java
  src/main/java/duke/items/tasks/Todo.java
  src/main/java/duke/items/tasks/Within.java
  src/test/java/AfterTest.java
  src/test/java/FileTest.java
  src/test/java/FixedTest.java
  src/test/java/GradedComponentTest.java
  src/test/java/RecurringTest.java
  src/test/java/ReminderCommandTest.java
  src/test/java/SnoozeTest.java
  src/test/java/StorageTest.java
  src/test/java/TentativeTest.java
  src/test/java/ViewScheduleTest.java
  src/test/java/WithinTest.java
Labels: priority.High, type.Tests

#69 Implement multiple command feature to carry out delete multiple or done multiple tasks function
  src/main/java/duke/Parser.java
  src/main/java/duke/commands/DeleteMultipleCommand.java
  src/main/java/duke/commands/MultipleCommand.java
  src/test/java/DukeTest.java
Labels: priority.High, type.Enhancement

#71 Refactor all Date parsing into DateTime
  src/main/java/duke/DateTime.java
  src/main/java/duke/Storage.java
  src/main/java/duke/commands/AddCommand.java
  src/main/java/duke/commands/FindFreeCommand.java
  src/main/java/duke/commands/SetCommand.java
  src/main/java/duke/commands/ViewScheduleCommand.java
  src/main/java/duke/items/tasks/Deadline.java
  src/main/java/duke/items/tasks/Event.java
  src/main/java/duke/items/tasks/Recurring.java
  src/main/java/duke/items/tasks/Task.java
  src/main/java/duke/items/tasks/Tentative.java
  src/main/java/duke/items/tasks/Within.java
  src/test/java/DateTimeTest.java
  src/test/java/RecurringTest.java
  src/test/java/ReminderCommandTest.java
  src/test/java/StorageTest.java
  src/test/java/TentativeTest.java
  src/test/java/TimeConflictTest.java
  src/test/java/ViewScheduleTest.java
  src/test/java/WithinTest.java
Labels: type.Refactor

#73 Add a basic module class
  src/main/java/duke/Module.java
  src/main/java/duke/commands/AddCommand.java
Labels: priority.High, v1.2

#81 Modify Task abstract class and its children according to architecture.
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/Storage.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/FileCommand.java
  src/main/java/spinbox/commands/FindFreeCommand.java
  src/main/java/spinbox/commands/ReminderCommand.java
  src/main/java/spinbox/commands/SetCommand.java
  src/main/java/spinbox/commands/ViewScheduleCommand.java
  src/main/java/spinbox/items/File.java
  src/main/java/spinbox/items/Item.java
  src/main/java/spinbox/items/tasks/After.java
  src/main/java/spinbox/items/tasks/Deadline.java
  src/main/java/spinbox/items/tasks/Event.java
  src/main/java/spinbox/items/tasks/Exam.java
  src/main/java/spinbox/items/tasks/Fixed.java
  src/main/java/spinbox/items/tasks/Lab.java
  src/main/java/spinbox/items/tasks/Lecture.java
  src/main/java/spinbox/items/tasks/NonSchedulable.java
  src/main/java/spinbox/items/tasks/Recurring.java
  src/main/java/spinbox/items/tasks/Schedulable.java
  src/main/java/spinbox/items/tasks/Task.java
  src/main/java/spinbox/items/tasks/TaskType.java
  src/main/java/spinbox/items/tasks/Tentative.java
  src/main/java/spinbox/items/tasks/Todo.java
  src/main/java/spinbox/items/tasks/Tutorial.java
  src/main/java/spinbox/items/tasks/Within.java
  src/main/java/spinbox/lists/FileList.java
  src/main/java/spinbox/lists/TaskList.java
  src/test/java/AfterTest.java
  src/test/java/FileTest.java
  src/test/java/FixedTest.java
  src/test/java/RecurringTest.java
  src/test/java/SnoozeTest.java
  src/test/java/SpinBoxTest.java
  src/test/java/StorageTest.java
  src/test/java/TentativeTest.java
  src/test/java/TimeConflictTest.java
  src/test/java/ViewScheduleTest.java
  src/test/java/WithinTest.java
Labels: v1.2

#83 Update command builder
  src/main/java/spinbox/Parser.java
Labels: priority.High

#85 Update module class
  src/main/java/spinbox/Module.java
Labels: priority.Low

#86 Parser into spinbox
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/Ui.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/ExitCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.High

#87 Implement hierarchy-based storage
  .gitignore
  src/main/java/spinbox/Module.java
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/Storage.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/DeleteCommand.java
  src/main/java/spinbox/commands/DoneCommand.java
  src/main/java/spinbox/commands/FileCommand.java
  src/main/java/spinbox/commands/MultipleCommand.java
  src/main/java/spinbox/commands/SetCommand.java
  src/main/java/spinbox/exceptions/CorruptedDataException.java
  src/main/java/spinbox/exceptions/FileCreationException.java
  src/main/java/spinbox/exceptions/StorageException.java
  src/main/java/spinbox/items/File.java
  src/main/java/spinbox/items/GradedComponent.java
  src/main/java/spinbox/items/Item.java
  src/main/java/spinbox/lists/FileList.java
  src/main/java/spinbox/lists/GradeList.java
  src/main/java/spinbox/lists/ModuleContainer.java
  src/main/java/spinbox/lists/SpinBoxList.java
  src/main/java/spinbox/lists/TaskList.java
  src/test/java/FileTest.java
  src/test/java/GradedComponentTest.java
  src/test/java/ModuleTest.java
  src/test/java/ReminderCommandTest.java
  src/test/java/StorageTest.java
Labels: priority.High, v1.2

#88 Implement notepad feature for modules
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/Storage.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/DeleteCommand.java
  src/main/java/spinbox/commands/DoneCommand.java
  src/main/java/spinbox/commands/ExitCommand.java
  src/main/java/spinbox/commands/FileCommand.java
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/commands/FindFreeCommand.java
  src/main/java/spinbox/commands/ListCommand.java
  src/main/java/spinbox/commands/MultipleCommand.java
  src/main/java/spinbox/commands/ReminderCommand.java
  src/main/java/spinbox/commands/SetCommand.java
  src/main/java/spinbox/commands/SnoozeCommand.java
  src/main/java/spinbox/commands/UnknownCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/commands/ViewScheduleCommand.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/Module.java
  src/main/java/spinbox/entities/Notepad.java
  src/main/java/spinbox/entities/items/File.java
  src/main/java/spinbox/entities/items/GradedComponent.java
  src/main/java/spinbox/entities/items/Item.java
  src/main/java/spinbox/entities/items/tasks/Deadline.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Exam.java
  src/main/java/spinbox/entities/items/tasks/Lab.java
  src/main/java/spinbox/entities/items/tasks/Lecture.java
  src/main/java/spinbox/entities/items/tasks/NonSchedulable.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
  src/main/java/spinbox/entities/items/tasks/Task.java
  src/main/java/spinbox/entities/items/tasks/TaskType.java
  src/main/java/spinbox/entities/items/tasks/Todo.java
  src/main/java/spinbox/entities/items/tasks/Tutorial.java
  src/main/java/spinbox/exceptions/CorruptedDataException.java
  src/main/java/spinbox/exceptions/DataReadWriteException.java
  src/main/java/spinbox/exceptions/InvalidIndexException.java
  src/main/java/spinbox/lists/SpinBoxList.java
  src/test/java/FileTest.java
  src/test/java/GradedComponentTest.java
  src/test/java/ModuleTest.java
  src/test/java/NotepadTest.java
  src/test/java/ReminderCommandTest.java
  src/test/java/StorageTest.java
  src/test/java/ViewScheduleTest.java
Labels: priority.Medium, v1.2

#89 Add minimal support for module addition
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/ExitCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/entities/Module.java
  src/test/java/ModuleTest.java
  src/test/java/NotepadTest.java
Labels: type.Task, type.Tests, v1.2

#91 Call sort method in add, replace, and mark
  src/main/java/spinbox/containers/lists/SpinBoxList.java
Labels: priority.Medium, type.Enhancement, v1.2

#90 Add files full
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
Labels: priority.High, type.Task, v1.2

#92 View lists when on tabs page
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
Labels: priority.High, type.Task, v1.2

#93 Enhance view command
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.Medium, type.Enhancement, v1.2

#94 Remove command for files
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.High, type.Bug, type.Task, v1.2

#95 Notepad commands
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/entities/Notepad.java
Labels: priority.High, type.Enhancement, v1.2

#97 Add Task Commands into Add Command
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.High, type.Task, v1.2

#103 Implement remove-multiple command, mark command for tasks and fix bugs
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/MarkCommand.java
  src/main/java/spinbox/commands/MultipleCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
Labels: priority.High, type.Bug, type.Task

#105 Fix duplication bug
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
Labels: severity.High, type.Bug

#104 Update jar version and deprecated api call
  build.gradle
  src/test/java/ViewScheduleTest.java
Labels: type.Refactor, type.Tests

#106 Fix typos
  src/main/java/spinbox/commands/MarkCommand.java
  src/main/java/spinbox/commands/MultipleCommand.java
Labels: type.Bug

#111 Update parser
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/MarkCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.High, type.Enhancement

#115 Update parser and commands
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/MarkCommand.java
  src/main/java/spinbox/commands/MultipleCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.High, severity.High, type.Bug, type.Refactor

#116 Implement Help Command
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
Labels: priority.High, type.Task

#121 Mark to update
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/DoneCommand.java
  src/main/java/spinbox/commands/FileCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/commands/UpdateCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/items/File.java
  src/main/java/spinbox/entities/items/GradedComponent.java
  src/main/java/spinbox/entities/items/Item.java
  src/main/java/spinbox/entities/items/tasks/Deadline.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Todo.java
Labels: priority.Medium, type.Refactor

#124 Implement different event type tasks and fix bug
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/commands/MultipleCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/UpdateCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Exam.java
  src/main/java/spinbox/entities/items/tasks/Lab.java
  src/main/java/spinbox/entities/items/tasks/Lecture.java
  src/main/java/spinbox/entities/items/tasks/Tutorial.java
Labels: priority.High, type.Refactor, type.Task

#123 Find command
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
Labels: priority.High, type.Story

#128 Implement UpdateMultiple Command
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/DeleteCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/commands/UpdateCommand.java
  src/main/java/spinbox/commands/UpdateMultipleCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.High, type.Refactor, type.Task

#129 Add functional GUI
  build.gradle
  src/main/Resources/view/MainWindow.css
  src/main/Resources/view/MainWindow.fxml
  src/main/Resources/view/ModuleListBox/ModuleListBox.css
  src/main/Resources/view/ModuleListBox/ModuleListBox.fxml
  src/main/Resources/view/itemBoxes/FileBox.fxml
  src/main/Resources/view/itemBoxes/TaskBox.fxml
  src/main/java/spinbox/Main.java
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/gui/MainWindow.java
  src/main/java/spinbox/gui/TaskBox.java
  src/main/java/spinbox/gui/boxes/FileBox.java
  src/main/java/spinbox/gui/boxes/ModuleBox.java
Labels: type.Epic, type.Refactor

#130 Implement SetName Command
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/commands/SetNameCommand.java
  src/main/java/spinbox/commands/SetTentativeCommand.java
  src/main/java/spinbox/commands/UpdateCommand.java
  src/main/java/spinbox/commands/UpdateMultipleCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/entities/Notepad.java
Labels: priority.High, type.Enhancement, type.Story

#136 Implement interface for containers w/ Storage
  build.gradle
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/ExitCommand.java
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/commands/FindFreeCommand.java
  src/main/java/spinbox/commands/ListCommand.java
  src/main/java/spinbox/commands/ReminderCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/commands/SetNameCommand.java
  src/main/java/spinbox/commands/SetTentativeCommand.java
  src/main/java/spinbox/commands/SnoozeCommand.java
  src/main/java/spinbox/commands/UnknownCommand.java
  src/main/java/spinbox/commands/ViewScheduleCommand.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/Notepad.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/Module.java
  src/main/java/spinbox/storage/StorableEntity.java
  src/main/java/spinbox/storage/Storage.java
  src/main/java/spinbox/storage/StorageContainer.java
  src/test/java/NotepadTest.java
  src/test/java/StorageTest.java
Labels: type.Refactor

#137 Set date command
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/FindFreeCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/commands/ListCommand.java
  src/main/java/spinbox/commands/ReminderCommand.java
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/commands/SetDateCommand.java
  src/main/java/spinbox/commands/SetNameCommand.java
  src/main/java/spinbox/commands/SetTentativeCommand.java
  src/main/java/spinbox/commands/SnoozeCommand.java
  src/main/java/spinbox/commands/UnknownCommand.java
  src/main/java/spinbox/commands/UpdateMultipleCommand.java
  src/main/java/spinbox/commands/ViewScheduleCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
Labels: priority.High, type.Enhancement, type.Story

#138 Restructure tests
  src/test/java/ReminderCommandTest.java
  src/test/java/ViewScheduleTest.java
  src/test/java/integration/ModuleIntegrationTest.java
  src/test/java/integration/NotepadIntegrationTest.java
  src/test/java/unit/DateTimeTest.java
  src/test/java/unit/FileTest.java
  src/test/java/unit/GradedComponentTest.java
  src/test/java/unit/ModuleTest.java
  src/test/java/unit/NotepadTest.java
  src/test/java/unit/ParserTest.java
  src/test/java/unit/StorageTest.java
  src/test/java/unit/ViewScheduleTest.java
Labels: type.Refactor, type.Tests

#139 Reorganize command
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/ExitCommand.java
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.Low, type.Refactor

#140 Implement export to text framework
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/ExportCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/entities/items/Item.java
  src/main/java/spinbox/exporter/Exportable.java
  src/main/java/spinbox/exporter/Exporter.java
  src/main/java/spinbox/storage/Storable.java
Labels: priority.High

#141 Parser view command integration test
  src/test/java/integration/ParserViewCommandIntegrationTest.java
  src/test/java/unit/ParserTest.java
Labels: priority.Medium, type.Tests

#143 Update Ui.png
  docs/images/Ui.png
Labels: priority.High, type.Documentation
