Repository AY1920S1-CS2113T-F14-4/main, pull requests merged in 2019-11, with the labels that each got.

#176 Fix Task Update in Gui
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.High, type.Bug

#177 Add line numbers and header to notes
  build.gradle
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.Medium

#178 Attempt add coverall integration
  .travis.yml
  README.adoc
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: type.Task

#179 Add storable interface and cleanup
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/Notepad.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/Module.java
  src/main/java/spinbox/entities/items/File.java
  src/main/java/spinbox/entities/items/GradedComponent.java
  src/main/java/spinbox/entities/items/Item.java
  src/main/java/spinbox/entities/items/tasks/Deadline.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Exam.java
  src/main/java/spinbox/entities/items/tasks/Lab.java
  src/main/java/spinbox/entities/items/tasks/Lecture.java
  src/main/java/spinbox/entities/items/tasks/NonSchedulable.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
  src/main/java/spinbox/entities/items/tasks/Task.java
  src/main/java/spinbox/entities/items/tasks/Todo.java
  src/main/java/spinbox/entities/items/tasks/Tutorial.java
  src/main/java/spinbox/storage/Storable.java
  src/test/java/unit/FileTest.java
  src/test/java/unit/GradedComponentTest.java
  src/test/java/unit/ModuleTest.java
Labels: type.Refactor

#180 Add tests to notepad
  src/test/java/unit/NotepadTest.java
Labels: type.Tests

#181 Implement support cross-platform JARs
  tutorials/javaFxTutorialPart1.md
Labels: priority.High

#182 Add Calendar view for month
  src/main/Resources/view/CalendarMonthBox.css
  src/main/Resources/view/CalendarMonthBox.fxml
  src/main/Resources/view/MainWindow.fxml
  src/main/java/spinbox/DateTime.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/Calendar.java
  src/main/java/spinbox/gui/CalendarMonthBox.java
  src/main/java/spinbox/gui/MainWindow.java
  src/test/java/unit/CalendarTest.java
  src/test/java/unit/DateTimeTest.java
Labels: priority.High, type.Epic

#183 Update gui tasks display
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.High, type.Enhancement

#185 Command integration test
  src/test/java/integration/TaskCommandsIntegrationTest.java
Labels: priority.High, type.Tests

#186 Command integration test
  src/test/java/integration/TaskCommandsIntegrationTest.java
Labels: priority.High, type.Tests

#188 File list integration test
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/test/java/integration/FileListIntegrationTest.java
Labels: priority.Low, type.Tests

#190 Task list integration test
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/test/java/unit/TaskListUnitTest.java
Labels: priority.Low, type.Tests

#192 File list integration test
  src/test/java/unit/FileListUnitTest.java
Labels: type.Refactor

#191 Modify Parser Test and Create Task Tests
  src/test/java/integration/FileListIntegrationTest.java
  src/test/java/integration/NotepadIntegrationTest.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
  src/test/java/unit/ParserTest.java
  src/test/java/unit/TaskTest.java
Labels: priority.Low, type.Tests

#194 Implement Remove Modules Command
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/test/java/integration/ModuleIntegrationTest.java
Labels: priority.High, type.Enhancement

#195 Update GUI to include index for files and grades view
  src/main/java/spinbox/gui/MainWindow.java
  src/main/java/spinbox/gui/boxes/FileBox.java
  src/main/java/spinbox/gui/boxes/GradedComponentBox.java
Labels: priority.Medium, type.Task

#196 Fix GUI bugs and update tests
  src/main/Resources/view/MainWindow.css
  src/main/Resources/view/MainWindow.fxml
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/gui/MainWindow.java
  src/test/java/integration/ParserViewCommandIntegrationTest.java
Labels: priority.Medium, severity.Low, type.Bug, type.Tests

#201 Update remove modules command
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/test/java/integration/ModuleIntegrationTest.java
Labels: priority.Medium, type.Task

#202 Implement export all deadlines
  src/main/java/spinbox/commands/ExportCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
Labels: priority.Low

#203 Fix popup blocking input box
  build.gradle
  src/main/Resources/view/MainWindow.css
  src/main/Resources/view/MainWindow.fxml
  src/main/java/spinbox/Main.java
  src/main/java/spinbox/gui/MainWindow.java
Labels: severity.Medium, type.Bug

#204 Add Exception for Schedulable
  src/main/java/spinbox/commands/SetDateCommand.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Exam.java
  src/main/java/spinbox/entities/items/tasks/Lab.java
  src/main/java/spinbox/entities/items/tasks/Lecture.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
  src/main/java/spinbox/entities/items/tasks/Tutorial.java
  src/main/java/spinbox/exceptions/ScheduleDateException.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
  src/test/java/unit/CalendarTest.java
  src/test/java/unit/TaskTest.java
  src/test/java/unit/ViewScheduleTest.java
Labels: severity.Low, type.Bug

#206 Add module code to calendar and main
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/Calendar.java
  src/main/java/spinbox/gui/CalendarMonthBox.java
  src/main/java/spinbox/gui/MainWindow.java
  src/test/java/unit/CalendarTest.java
Labels: priority.Medium, severity.Low, type.Enhancement

#205 Add command to populate sample data
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/Command.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/commands/PopulateCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/commands/ScoreCommand.java
  src/main/java/spinbox/commands/SetDateCommand.java
  src/main/java/spinbox/commands/SetNameCommand.java
  src/main/java/spinbox/commands/UpdateCommand.java
  src/main/java/spinbox/commands/UpdateMultipleCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.High

#208 Add ExamView to Main
  src/main/Resources/view/MainWindow.fxml
  src/main/Resources/view/itemBoxes/TaskBox.fxml
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/Calendar.java
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.High, type.Story

#207 Implement Cross Platform Support for SpinBox
  build.gradle
Labels: priority.High

#209 Add Exception Handling
  src/main/java/spinbox/entities/items/tasks/Deadline.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Exam.java
  src/main/java/spinbox/entities/items/tasks/Lab.java
  src/main/java/spinbox/entities/items/tasks/Lecture.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
  src/main/java/spinbox/entities/items/tasks/Tutorial.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
  src/test/java/unit/CalendarTest.java
  src/test/java/unit/TaskTest.java
  src/test/java/unit/ViewScheduleTest.java
Labels: priority.High, type.Bug

#210 Add assertations and fortify GUI
  src/main/Resources/view/CalendarMonthBox.fxml
  src/main/Resources/view/DialogBox.fxml
  src/main/Resources/view/MainWindow.fxml
  src/main/Resources/view/ModuleListBox/ModuleListBox.fxml
  src/main/Resources/view/itemBoxes/FileBox.fxml
  src/main/Resources/view/itemBoxes/GradedComponentBox.fxml
  src/main/Resources/view/itemBoxes/TaskBox.fxml
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/entities/items/File.java
  src/main/java/spinbox/entities/items/GradedComponent.java
  src/main/java/spinbox/entities/items/tasks/NonSchedulable.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
  src/main/java/spinbox/exporter/Exporter.java
  src/main/java/spinbox/gui/MainWindow.java
  src/main/java/spinbox/storage/Storage.java
Labels: severity.Medium, type.Refactor

#211 Propagate corrupted data GUI warning
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.High, type.Refactor

#212 Edit Test Module Name and Add Integration Tests
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/commands/UpdateMultipleCommand.java
  src/test/java/integration/FileListIntegrationTest.java
  src/test/java/integration/ModuleIntegrationTest.java
  src/test/java/integration/NotepadIntegrationTest.java
  src/test/java/integration/ParserViewCommandIntegrationTest.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
Labels: priority.High, type.Tests

#213 Incorporate logging
  src/main/java/spinbox/Main.java
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/SpinBox.java
  src/main/java/spinbox/entities/items/GradedComponent.java
  src/main/java/spinbox/exporter/Exporter.java
  src/main/java/spinbox/gui/MainWindow.java
  src/main/java/spinbox/storage/Storage.java
Labels: priority.High, type.Task

#215 Extract out filehandlers
  src/main/java/spinbox/commands/ExitCommand.java
  src/main/java/spinbox/commands/ExportCommand.java
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/containers/ModuleContainer.java
  src/main/java/spinbox/containers/Notepad.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/main/java/spinbox/datapersistors/FileDataWriter.java
  src/main/java/spinbox/datapersistors/exporter/ExportConverter.java
  src/main/java/spinbox/datapersistors/exporter/Exportable.java
  src/main/java/spinbox/datapersistors/exporter/Exporter.java
  src/main/java/spinbox/datapersistors/storage/Storable.java
  src/main/java/spinbox/datapersistors/storage/Storage.java
  src/main/java/spinbox/datapersistors/storage/StorageContainer.java
  src/main/java/spinbox/entities/Module.java
  src/main/java/spinbox/entities/items/Item.java
  src/test/java/unit/ExportConverterTest.java
  src/test/java/unit/StorageTest.java
  src/test/java/unit/TaskListUnitTest.java
Labels: type.Refactor

#214 Refactor Parser
  src/main/java/spinbox/Parser.java
Labels: priority.Medium, type.Refactor

#216 Add Exception handling to DateTime
  src/main/java/spinbox/DateTime.java
  src/main/java/spinbox/commands/SetDateCommand.java
  src/main/java/spinbox/commands/SetNameCommand.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/datapersistors/storage/Storable.java
  src/main/java/spinbox/datapersistors/storage/StorageContainer.java
  src/main/java/spinbox/entities/Calendar.java
  src/main/java/spinbox/entities/Module.java
  src/main/java/spinbox/entities/items/tasks/Deadline.java
  src/main/java/spinbox/entities/items/tasks/Event.java
  src/main/java/spinbox/entities/items/tasks/Exam.java
  src/main/java/spinbox/entities/items/tasks/Lab.java
  src/main/java/spinbox/entities/items/tasks/Lecture.java
  src/main/java/spinbox/entities/items/tasks/Schedulable.java
  src/main/java/spinbox/entities/items/tasks/Tutorial.java
  src/main/java/spinbox/exceptions/CalendarSelectorException.java
  src/main/java/spinbox/gui/CalendarMonthBox.java
  src/main/java/spinbox/gui/DialogBox.java
  src/main/java/spinbox/gui/MainWindow.java
  src/test/java/integration/ModuleIntegrationTest.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
  src/test/java/unit/CalendarTest.java
  src/test/java/unit/DateTimeTest.java
  src/test/java/unit/FileTest.java
  src/test/java/unit/ModuleTest.java
  src/test/java/unit/TaskTest.java
  src/test/java/unit/ViewScheduleTest.java
Labels: priority.Medium, severity.Low, type.Bug

#218 Refactor List Classes
  src/main/java/spinbox/commands/AddCommand.java
  src/main/java/spinbox/commands/RemoveCommand.java
  src/main/java/spinbox/commands/RemoveMultipleCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
  src/test/java/integration/FileListIntegrationTest.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
  src/test/java/unit/FileListUnitTest.java
  src/test/java/unit/TaskListUnitTest.java
Labels: priority.Medium, type.Refactor

#217 Integration Tests for Help Command and Help List
  src/main/java/spinbox/Parser.java
  src/test/java/integration/HelpCommandIntegrationTest.java
Labels: priority.Medium, type.Tests

#219 Update GUI for Main Page
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.Medium, type.Task

#220 Refactor view command
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.Medium, type.Refactor

#221 Improve Calendar GUI and view command
  src/main/Resources/view/CalendarMonthBox.fxml
  src/main/Resources/view/MainWindow.fxml
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/entities/Calendar.java
  src/main/java/spinbox/gui/CalendarMonthBox.java
  src/main/java/spinbox/gui/MainWindow.java
Labels: priority.Medium

#222 Small refactor
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.Low, type.Refactor

#223 Find grade
  src/main/java/spinbox/commands/FindCommand.java
  src/main/java/spinbox/commands/HelpCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/HelpList.java
  src/main/java/spinbox/containers/lists/TaskList.java
Labels: priority.High, type.Enhancement

#227 Find command whitespace
  src/main/java/spinbox/commands/FindCommand.java
Labels: priority.High, type.Bug, type.Refactor

#228 Refactor Find Command
  src/main/java/spinbox/commands/FindCommand.java
Labels: priority.Medium, type.Refactor

#229 Update release filename
  build.gradle
Labels: release.Jar

#230 Refactor Test Codes and Set Date
  src/main/java/spinbox/Parser.java
  src/main/java/spinbox/commands/SetDateCommand.java
  src/main/java/spinbox/commands/SetNameCommand.java
  src/main/java/spinbox/gui/MainWindow.java
  src/test/java/integration/HelpCommandIntegrationTest.java
  src/test/java/integration/NotepadIntegrationTest.java
  src/test/java/integration/TaskCommandsIntegrationTest.java
Labels: type.Refactor

#231 Typo
  src/main/java/spinbox/commands/ViewCommand.java
  src/main/java/spinbox/containers/lists/FileList.java
  src/main/java/spinbox/containers/lists/GradeList.java
  src/main/java/spinbox/containers/lists/SpinBoxList.java
  src/main/java/spinbox/containers/lists/TaskList.java
Labels: priority.Low, type.Refactor

#232 View calendar refactor
  src/main/java/spinbox/commands/ViewCommand.java
Labels: priority.Low, type.Refactor
